/*
 * Lamblin
 * Copyright 2018 Borislav Shekerov
 * Licensed under Apache 2.0: https://github.com/BorislavShekerov/lamblin/blob/master/LICENSE
 */

package com.lamblin.core.model

const val OK_CODE = 200
const val CREATED_CODE = 201
const val ACCEPTED_CODE = 202
const val NON_AUTHORITATIVE_INFORMATION_CODE = 203
const val NO_CONTENT_CODE = 204
const val RESET_CONTENT_CODE = 204
const val PARTIAL_CONTENT_CODE = 204

const val MULTIPLE_CHOICES_CODE = 300
const val MOVED_PERMANENTLY_CODE = 301
const val FOUND_CODE = 302
const val SEE_OTHER_CODE = 303
const val NOT_MODIFIED_CODE = 304
const val USE_PROXY_CODE = 305
const val SWITCH_PROXY_CODE = 306
const val TEMPORARY_REDIRECT_CODE = 307
const val PERMANENT_REDIRECT_CODE = 308

const val BAD_REQUEST_CODE = 400
const val UNAUTHORIZED_CODE = 401
const val PAYMENT_REQUIRED_CODE = 402
const val FORBIDDEN_CODE = 403
const val NOT_FOUND_CODE = 404
const val METHOD_NOT_ALLOWED_CODE = 405
const val METHOD_NOT_ACCEPTED_CODE = 406
const val PROXY_AUTHENTICATION_REQUIRED_CODE = 407
const val REQUEST_TIMEOUT_CODE = 408
const val CONFLICT_CODE = 409
const val GONE_CODE = 410

const val API_ERROR_CODE = 500
const val NOT_IMPLEMENTED_CODE = 501
const val BAD_GATEWAY_CODE = 502
const val SERVICE_UNAVAILABLE_CODE = 503

/** Defines the status codes supported. */
enum class StatusCode(val code: Int) {
    OK(OK_CODE),
    CREATED(CREATED_CODE),
    ACCEPTED(ACCEPTED_CODE),
    NON_AUTHORITATIVE_INFORMATION(NON_AUTHORITATIVE_INFORMATION_CODE),
    NO_CONTENT(NO_CONTENT_CODE),
    RESET_CONTENT(RESET_CONTENT_CODE),
    PARTIAL_CONTENT(PARTIAL_CONTENT_CODE),

    MULTIPLE_CHOICES(MULTIPLE_CHOICES_CODE),
    MOVED_PERMANENTLY(MOVED_PERMANENTLY_CODE),
    FOUND(FOUND_CODE),
    SEE_OTHER(SEE_OTHER_CODE),
    NOT_MODIFIED(NOT_MODIFIED_CODE),
    USE_PROXY(USE_PROXY_CODE),
    SWITCH_PROXY(SWITCH_PROXY_CODE),
    TEMPORARY_REDIRECT(TEMPORARY_REDIRECT_CODE),
    PERMANENT_REDIRECT(PERMANENT_REDIRECT_CODE),

    BAD_REQUEST(BAD_REQUEST_CODE),
    UNAUTHORIZED(UNAUTHORIZED_CODE),
    PAYMENT_REQUIRED(PAYMENT_REQUIRED_CODE),
    FORBIDDEN(FORBIDDEN_CODE),
    NOT_FOUND(NOT_FOUND_CODE),
    METHOD_NOT_ALLOWED(METHOD_NOT_ALLOWED_CODE),
    METHOD_NOT_ACCEPTED(METHOD_NOT_ACCEPTED_CODE),
    PROXY_AUTHENTICATION_REQUIRED(PROXY_AUTHENTICATION_REQUIRED_CODE),
    REQUEST_TIMEOUT(REQUEST_TIMEOUT_CODE),
    CONFLICT(CONFLICT_CODE),
    GONE(GONE_CODE),

    API_ERROR(API_ERROR_CODE),
    NOT_IMPLEMENTED(NOT_IMPLEMENTED_CODE),
    BAD_GATEWAY(BAD_GATEWAY_CODE),
    SERVICE_UNAVAILABLE(SERVICE_UNAVAILABLE_CODE)
}
